const employee = [
  {
    id: 1,
    firstName: "Aarav",
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        title: "Design Homepage",
        description: "Create the homepage layout in Figma.",
        taskDate: "2025-10-20",
        category: "Design",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Client Meeting",
        description: "Discuss UI requirements with the client.",
        taskDate: "2025-10-22",
        category: "Meeting",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Fix Navbar Bug",
        description: "Resolve alignment issue in navbar on mobile.",
        taskDate: "2025-10-25",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 2,
    firstName: "Priya",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        title: "API Integration",
        description: "Integrate the payment API into checkout page.",
        taskDate: "2025-10-19",
        category: "Backend",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Unit Testing",
        description: "Write Jest tests for product module.",
        taskDate: "2025-10-24",
        category: "Testing",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Fix Login Issue",
        description: "Resolve incorrect password validation bug.",
        taskDate: "2025-10-18",
        category: "Bug Fix",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Optimize Images",
        description: "Compress and optimize product images for speed.",
        taskDate: "2025-10-26",
        category: "Performance",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 3,
    firstName: "Rohan",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        title: "Database Cleanup",
        description: "Remove unused tables and optimize queries.",
        taskDate: "2025-10-15",
        category: "Database",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Add Dark Mode",
        description: "Implement dark mode toggle feature.",
        taskDate: "2025-10-20",
        category: "Frontend",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Refactor Auth Logic",
        description: "Clean up login and logout logic in Redux.",
        taskDate: "2025-10-23",
        category: "Refactor",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Fix Loader Animation",
        description: "Loader not showing on slow networks.",
        taskDate: "2025-10-26",
        category: "UI/UX",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 4,
    firstName: "Sneha",
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        title: "Update Documentation",
        description: "Write README for setup instructions.",
        taskDate: "2025-10-10",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Deploy App",
        description: "Deploy to production using Vercel.",
        taskDate: "2025-10-18",
        category: "Deployment",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "SEO Improvements",
        description: "Add meta tags and improve page titles.",
        taskDate: "2025-10-21",
        category: "SEO",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Fix Console Warnings",
        description: "Resolve React key warnings and unused imports.",
        taskDate: "2025-10-22",
        category: "Maintenance",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Add Analytics",
        description: "Integrate Google Analytics v4.",
        taskDate: "2025-10-25",
        category: "Analytics",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 2,
      failed: 1,
    },
  },
  {
    id: 5,
    firstName: "Vikram",
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        title: "Customer Feedback",
        description: "Collect feedback from 10 recent users.",
        taskDate: "2025-10-12",
        category: "Research",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "New Landing Page",
        description: "Design and develop new product landing page.",
        taskDate: "2025-10-19",
        category: "Design",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Fix Footer Links",
        description: "Update privacy policy and terms link.",
        taskDate: "2025-10-22",
        category: "UI Fix",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Add Email Notifications",
        description: "Trigger emails for order status changes.",
        taskDate: "2025-10-25",
        category: "Backend",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Logo Update",
        description: "Replace old logo with the new company logo.",
        taskDate: "2025-10-27",
        category: "Branding",
        active: false,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employee", JSON.stringify(employee));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employee = JSON.parse(localStorage.getItem("employee"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employee, admin };
};
